#!/usr/bin/env python3
"""
SessionStart hook for the AI Sector Research OS.

At session start, surfaces:
- Top 5 open to-do items by priority + artifact-producing + tag count + age
- Always surfaces P0 items even if not in top 5
- Pending grades (predictions past resolution date)
- Stale reviews (bottlenecks.md last_review > 30 days)

Output goes to stdout, which Claude Code injects into the new session's
context. Always exits 0 (informational, never blocking).

Scope: only enforces when in /home/user/Health-Calculators.
"""

import json
import os
import re
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

ENFORCEMENT_PATHS = ["/home/user/Health-Calculators"]
TODO_PATH = Path("/home/user/Health-Calculators/research/meta/todo.md")
PREDICTIONS_LOG_PATH = Path("/home/user/Health-Calculators/research/predictions/grading-log.md")
BOTTLENECKS_PATH = Path("/home/user/Health-Calculators/research/sector/bottlenecks.md")

REPO_PATH = Path("/home/user/Health-Calculators")

# Priority sort: lower = higher priority
PRIORITY_RANK = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}

# Artifact-producing categories rank higher than process categories
ARTIFACT_CATEGORIES = {"prediction", "research", "wiki", "verification"}
PROCESS_CATEGORIES = {"harness", "infra"}


def in_scope() -> bool:
    cwd = os.getcwd()
    return any(cwd.startswith(p) for p in ENFORCEMENT_PATHS)


def parse_todo_items(text: str) -> list[dict]:
    """
    Parse open to-do items from todo.md.

    Each item starts with `- [ ] **P0 / category / 2026-05-20** [TAGS] — Title`
    followed by 1+ indented bullet sub-lines.
    """
    items = []
    # Match the header line, capturing priority, category, date, tags (optional), and title
    header_re = re.compile(
        r"^- \[ \] \*\*(P[0-3])\s*/\s*(\w+)\s*/\s*(\d{4}-\d{2}-\d{2})\*\*"
        r"(?:\s*\[([^\]]*)\])?"
        r"\s*—\s*(.+)$",
        re.MULTILINE,
    )
    for m in header_re.finditer(text):
        priority, category, date_str, tags_raw, title = m.groups()
        tags = []
        if tags_raw:
            tags = [t.strip() for t in tags_raw.split(",") if t.strip()]
        items.append({
            "priority": priority,
            "category": category.lower(),
            "date": date_str,
            "tags": tags,
            "title": title.strip(),
        })
    return items


def sort_key(item: dict) -> tuple:
    """
    Sort: priority asc, artifact-producing first, tag count desc, date asc.
    """
    p_rank = PRIORITY_RANK.get(item["priority"], 99)
    is_artifact = 0 if item["category"] in ARTIFACT_CATEGORIES else 1
    tag_count_neg = -len(item["tags"])  # negative for descending sort
    return (p_rank, is_artifact, tag_count_neg, item["date"])


def parse_pending_predictions(text: str) -> list[dict]:
    """
    Pending predictions: items in the `## Pending` section of grading-log.md
    with a resolution date <= today.
    """
    today = date.today()
    pending = []
    # Find the Pending section
    pending_section_re = re.compile(
        r"##\s*Pending\s*\n(.*?)(?=\n##|\Z)", re.DOTALL | re.IGNORECASE
    )
    m = pending_section_re.search(text)
    if not m:
        return pending
    section = m.group(1)
    # Table rows look like: | YYYY-MM-DD | YYYY-MM-DD | TICKER | EVENT | FILE | DIRECTION |
    row_re = re.compile(
        r"^\|\s*(\d{4}-\d{2}-\d{2})\s*\|\s*(\d{4}-\d{2}-\d{2})[^|]*\|\s*([A-Z]+)\s*\|\s*([^|]+)\s*\|",
        re.MULTILINE,
    )
    for row in row_re.finditer(section):
        made, resolution, ticker, event = row.groups()
        try:
            res_date = datetime.strptime(resolution, "%Y-%m-%d").date()
        except ValueError:
            continue
        if res_date <= today:
            pending.append({
                "made": made,
                "resolution": resolution,
                "ticker": ticker.strip(),
                "event": event.strip(),
            })
    return pending


def parse_bottlenecks_last_review(text: str) -> date | None:
    """Find `last_review: YYYY-MM-DD` field in bottlenecks.md."""
    m = re.search(r"last_review[:\s]+(\d{4}-\d{2}-\d{2})", text, re.IGNORECASE)
    if not m:
        return None
    try:
        return datetime.strptime(m.group(1), "%Y-%m-%d").date()
    except ValueError:
        return None


def format_item(item: dict) -> str:
    tags = ", ".join(item["tags"]) if item["tags"] else "—"
    return f"  {item['priority']} / {item['category']} / {item['date']} [{tags}] — {item['title']}"


def build_briefing() -> str | None:
    lines = []
    lines.append("=== SESSION START BRIEFING (auto-generated by session-start-hook.py) ===")
    lines.append("")
    lines.append(f"Working directory: {os.getcwd()}")
    lines.append(f"Today: {date.today().isoformat()}")
    lines.append("")

    # To-do items
    if TODO_PATH.exists():
        text = TODO_PATH.read_text()
        items = parse_todo_items(text)
        if items:
            items.sort(key=sort_key)
            p0_items = [i for i in items if i["priority"] == "P0"]
            top5 = items[:5]

            lines.append(f"TO-DO STATUS: {len(items)} open items")
            lines.append("")

            if p0_items:
                lines.append("P0 ITEMS (always surfaced):")
                for it in p0_items:
                    lines.append(format_item(it))
                lines.append("")

            # Top 5 (de-duplicate from P0 items already shown)
            top5_non_p0 = [i for i in top5 if i["priority"] != "P0"]
            if top5_non_p0:
                lines.append("TOP OPEN ITEMS (after P0):")
                for it in top5_non_p0:
                    lines.append(format_item(it))
                lines.append("")
        else:
            lines.append("TO-DO STATUS: no open items found in todo.md")
            lines.append("")
    else:
        lines.append(f"TO-DO STATUS: todo.md not found at {TODO_PATH}")
        lines.append("")

    # Pending predictions
    if PREDICTIONS_LOG_PATH.exists():
        text = PREDICTIONS_LOG_PATH.read_text()
        pending = parse_pending_predictions(text)
        if pending:
            lines.append("PENDING GRADES (predictions past resolution date):")
            for p in pending:
                lines.append(f"  {p['ticker']} {p['event']} — predicted {p['made']}, resolved {p['resolution']}")
            lines.append("")

    # Bottlenecks last review
    if BOTTLENECKS_PATH.exists():
        text = BOTTLENECKS_PATH.read_text()
        last_review = parse_bottlenecks_last_review(text)
        if last_review:
            days_since = (date.today() - last_review).days
            if days_since > 30:
                lines.append(
                    f"STALE REVIEW: bottlenecks.md last_review {last_review.isoformat()} "
                    f"({days_since} days ago — run BOTTLENECK-FORECAST workflow)"
                )
                lines.append("")

    lines.append("Read /home/user/Health-Calculators/research/meta/todo.md for full backlog.")
    lines.append("=== END BRIEFING ===")
    return "\n".join(lines)


def main():
    # Read and discard stdin (we don't need session metadata for v1)
    try:
        sys.stdin.read()
    except Exception:
        pass

    if not in_scope():
        sys.exit(0)

    try:
        briefing = build_briefing()
        if briefing:
            print(briefing)
    except Exception as e:
        # Never break a session because of the hook. Log to stderr and pass.
        print(f"session-start-hook error: {e}", file=sys.stderr)

    sys.exit(0)


if __name__ == "__main__":
    main()
